# Generated by Django 5.1.1 on 2024-11-20 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0003_initial'),
        ('user_profile', '0003_rename_user_status_profileinfo_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profileinfo'),
        ),
    ]
