# Generated by Django 5.1.1 on 2024-12-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_page', '0004_alter_emailconfirmation_user'),
        ('user_profile', '0005_remove_profileinfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profileinfo')),
            ],
        ),
    ]
