# Generated by Django 5.1.1 on 2024-10-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_remove_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
