# Generated by Django 5.1.1 on 2024-10-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='license_number',
        ),
    ]
