# Generated by Django 5.1.1 on 2024-11-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0005_alter_rentalrecord_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentalrecord',
            name='payment_in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
