# Generated by Django 5.1.1 on 2024-11-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0006_rentalrecord_is_rated'),
        ('rental_record', '0006_rentalrecord_payment_due_date_and_more'),
    ]

    operations = [
    ]
