# Generated by Django 5.1.1 on 2024-11-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0007_merge_20241119_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrecord',
            name='return_status',
        ),
        migrations.AddField(
            model_name='rentalrecord',
            name='rental_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('booked', 'Booked'), ('in_use', 'In_use'), ('returned', 'Returned'), ('overdue_pending', 'Overdue_pending'), ('overdue_returned', 'Overdue_returned'), ('overdue_extended', 'Overdue_extended'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
