# Generated by Django 5.1.1 on 2024-11-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0009_alter_rentalrecord_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrecord',
            name='rental_status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('pending', 'Pending'), ('booked', 'Booked'), ('in_use', 'In_use'), ('returned', 'Returned'), ('overdue_pending', 'Overdue_pending'), ('overdue_returned', 'Overdue_returned'), ('overdue_extended', 'Overdue_extended'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
