# Generated by Django 5.1.1 on 2024-11-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0011_alter_rentalrecord_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
