# Generated by Django 5.1.1 on 2024-11-30 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0014_alter_rentalrecord_rental_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalrecord',
            name='return_status',
        ),
    ]
