# Generated by Django 5.1.1 on 2024-11-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0015_remove_rentalrecord_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrecord',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentalrecord',
            name='start_date',
            field=models.DateField(),
        ),
    ]
