# Generated by Django 5.1.1 on 2024-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_record', '0016_alter_rentalrecord_return_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrecord',
            name='transaction_id',
            field=models.BigIntegerField(editable=False, null=True, unique=True),
        ),
    ]
