# Generated by Django 5.1.1 on 2024-11-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profileinfo_user_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileinfo',
            old_name='user_status',
            new_name='email_verified',
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='license_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profileinfo',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
