# Generated by Django 5.1.1 on 2024-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_user_status_profileinfo_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
