# Generated by Django 5.1.1 on 2024-12-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_rename_user_status_profileinfo_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
