# Generated by Django 5.1.1 on 2024-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profileinfo_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='is_deleted',
        ),
    ]
