# Generated by Django 5.1.1 on 2024-10-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='license_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
