# Generated by Django 5.1.1 on 2024-12-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_profileinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='license_no',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
