# Generated by Django 5.1.1 on 2024-12-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_profileinfo_license_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileinfo',
            name='license_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
