# Generated by Django 5.1.1 on 2024-12-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profileinfo_license_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
