# Generated by Django 5.1.1 on 2024-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_price', models.FloatField(default=0.0)),
                ('vehicle_status', models.CharField(max_length=20)),
            ],
        ),
    ]
