# Generated by Django 5.1.1 on 2024-09-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'Available'), ('in use', 'In Use')], default='Available', max_length=20),
        ),
    ]
