# Generated by Django 5.1.1 on 2024-09-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('available', 'Available'), ('in use', 'In Use')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4', '4 seater'), ('6', '6 seater'), ('1', 'Motorcycle')], max_length=50),
        ),
    ]
