# Generated by Django 5.1.1 on 2024-09-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_vehicle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4 seater', '4 seater'), ('6 seater', '6 seater'), ('1 seater', 'Motorcycle')], max_length=50),
        ),
    ]
