# Generated by Django 5.1.1 on 2024-10-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_vehicle_vehicle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_blobimage',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(max_length=10),
        ),
    ]
