# Generated by Django 5.1.1 on 2024-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_vehicle_blobimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_blobimage',
        ),
    ]
