# Generated by Django 5.1.1 on 2024-10-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_remove_vehicle_vehicle_blobimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_blobimage',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
