# Generated by Django 5.1.1 on 2024-10-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_vehicle_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(max_length=100),
        ),
    ]
