# Generated by Django 5.1.1 on 2024-10-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_vehicle_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('4 seater', '4 seater'), ('6 seater', '6 seater'), ('1 seater', 'Motorcycle')], max_length=50)),
                ('vehicle_price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_brand',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_price',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='vehicles.vehiclemodel'),
        ),
    ]
