# Generated by Django 5.1.1 on 2024-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehiclemodel_remove_vehicle_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_blobimage',
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_blobimage',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemodel',
            name='vehicle_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
