# Generated by Django 5.1.1 on 2024-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_alter_vehicle_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4 seater', '4 seater'), ('6 seater', '6 seater'), ('2 seater', 'Motorcycle')], max_length=50),
        ),
    ]
