# Generated by Django 5.1.1 on 2024-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_vehicle_vehicle_cargo_vehicle_vehicle_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_rating',
            field=models.FloatField(default=0),
        ),
    ]
