# Generated by Django 5.1.1 on 2024-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_fuel',
            field=models.CharField(choices=[('Gasoline Petrol', 'Gasoline Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_cargo',
            field=models.CharField(choices=[('12.6 cu ft', 'Standard Cargo Capacity'), ('38.5 cu ft', 'Expanded Cargo Capacity'), ('75.5 cu ft', 'Max Cargo Capacity')], max_length=50, null=True),
        ),
    ]
