# Generated by Django 5.1.1 on 2024-12-09 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_vehicle_vehicle_fuel_alter_vehicle_vehicle_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
