# Generated by Django 5.1.1 on 2024-10-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_brand', models.CharField(max_length=10)),
                ('vehicle_type', models.CharField(choices=[('4 seater', '4 seater'), ('6 seater', '6 seater'), ('1 seater', 'Motorcycle')], max_length=50)),
                ('vehicle_price', models.FloatField(default=0.0)),
                ('vehicle_status', models.CharField(choices=[('Available', 'Available'), ('In Use', 'In Use')], default='Available', max_length=20)),
                ('vehicle_blobimage', models.BinaryField(default=b'')),
            ],
        ),
    ]
