# Generated by Django 5.1.1 on 2024-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations_for_vehicles', '0002_remove_vehicle_vehicle_blobimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('4 seater', '4 seater'), ('6 seater', '6 seater'), ('Motorcycle', 'Motorcycle')], max_length=50),
        ),
    ]
