# Generated by Django 5.1.1 on 2024-10-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations_for_vehicles', '0003_alter_vehicle_vehicle_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Vehiclee',
        ),
    ]
