# Generated by Django 5.1.1 on 2024-10-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_operations_for_vehicles', '0004_rename_vehicle_vehiclee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehiclee',
        ),
    ]
